[credentials]
[credentials.usernames]

[credentials.usernames.dp]
failed_login_attempts = 0
logged_in = false
name = "Duncan Penn"
password = "$2b$12$kzceQSRM87SufyAZb27NA.YIUbXhglhdtz41SrnM6e73KqKXHwqe2"

[credentials.usernames.ohm]
failed_login_attempts = 0
logged_in = false
name = "Oliver Marler"
password = "$2b$12$YSoNG.IHlVdpr87gphyBtuYtHo8s3zCVVeBoAf0KhKSJo/wfjWxoS"

[cookie]
expiry_days = 30
key = "c2b33e0001786931e861c116d07ddd4b"
name = "user_authentication_cookie"